import { connectDb } from "./connectDb";
import { Recipe } from "./models";

export const companyData = {
  brandName: "Gourmish",
  tagline: "Food Recipes",
  metaDescription:
    "Discover delicious and easy-to-follow recipes on Gourmish. From savory meals to sweet treats, explore a world of culinary inspiration with step-by-step guides, tips, and mouth-watering photos. Perfect for home cooks and food enthusiasts alike!",
  favicon: "/favicon.png",
  logoMain: "/logo-main.svg",
  logoDark: "/logo-dark.svg",
  logoWhite: "/logo-white.svg",
};

export const defaultData = {
  defaultUserAvatar: "",
  defaultUserFirstName: "John",
  defaultUserLastName: "Doe",
};

export const menuLinks = [
  { title: "Recipes", path: "/recipes" },
  { title: "Categories", path: "/" },
  { title: "Favorites", path: "/" },
  { title: "Lists", path: "/" },
];

export const recipes = [
  {
    id: 1,
    title: "Easy Meatballs with Arugula",
    featuredImage:
      "https://images.unsplash.com/photo-1529042410759-befb1204b468?q=80&w=1972&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cuisine: ["Italian"],
    cookingMethod: ["Fried"],
    courses: ["Main Course"],
    prepTime: "20 mins",
    cookTime: "15 mins",
    servings: "2",
    nutritionFacts: {
      calories: "286",
      fat: "22g",
      carbs: "8g",
      protein: "15g",
    },
    tags: [],
    desc: "",
    ingredients: [
      "1.5Kg beef in 5cm pieces",
      "5 salam leaves",
      "2 sticks of lemongrass",
      "25gr dried coconut flakes",
      "200ml pineapple juice or oj",
      "1liter santen (coconut milk)",
      "4 red peppers or 2 habanero",
      "3tbps coriander seeds",
      "5cm piece of laos grated",
      "10cm ginger grated",
      "1tbsp koenjit",
      "10 cloves of garlic",
      "4 red peppers or 2 habanero",
      "Lomboks to taste (optional)",
    ],
    directions: [
      "In a kitchen mixer add peppers, garlic, laos, ginger, and the koenjit and blend to a paste",
      "Take the paste and rub it into the beef",
      "Take the beef and santen and bring to a soft boil",
      "Add the salam leaves and lemongrass(bruised) and simmer on low for 2 hours",
      "Taste add optional lomboks and salt and simmer 1 more hour stirring occasionally",
      "When the liquid has evaporated and oil floats to the top and the meat is golden brown its done",
      "Toast the coconut flakes and stir it into the stew",
      "During the cooling down the meat will soak up the liquid we rehydrate this with the pineapple juice",
    ],
    notes:
      "This is my personal favorite disg and version. Definitely recommend experimenting Add lomboks for spice or green tea for additional flavor",
    views: 200,
  },
  {
    id: 2,
    title: "Best Steak & Veggies",
    featuredImage:
      "https://images.unsplash.com/photo-1633436375795-12b3b339712f?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cuisine: ["American"],
    cookingMethod: ["Fried"],
    courses: ["Main Course"],
    prepTime: "20 mins",
    cookTime: "15 mins",
    servings: "2",
    nutritionFacts: {
      calories: "286",
      fat: "22g",
      carbs: "8g",
      protein: "15g",
    },
    tags: [],
    desc: "",
    ingredients: [
      "1.5Kg beef in 5cm pieces",
      "5 salam leaves",
      "2 sticks of lemongrass",
      "25gr dried coconut flakes",
      "200ml pineapple juice or oj",
      "1liter santen (coconut milk)",
      "4 red peppers or 2 habanero",
      "3tbps coriander seeds",
      "5cm piece of laos grated",
      "10cm ginger grated",
      "1tbsp koenjit",
      "10 cloves of garlic",
      "4 red peppers or 2 habanero",
      "Lomboks to taste (optional)",
    ],
    directions: [
      "In a kitchen mixer add peppers, garlic, laos, ginger, and the koenjit and blend to a paste",
      "Take the paste and rub it into the beef",
      "Take the beef and santen and bring to a soft boil",
      "Add the salam leaves and lemongrass(bruised) and simmer on low for 2 hours",
      "Taste add optional lomboks and salt and simmer 1 more hour stirring occasionally",
      "When the liquid has evaporated and oil floats to the top and the meat is golden brown its done",
      "Toast the coconut flakes and stir it into the stew",
      "During the cooling down the meat will soak up the liquid we rehydrate this with the pineapple juice",
    ],
    notes:
      "This is my personal favorite disg and version. Definitely recommend experimenting Add lomboks for spice or green tea for additional flavor",
    views: 200,
  },
  {
    id: 3,
    title: "Baked Eggs in a Blanket",
    featuredImage:
      "https://images.unsplash.com/photo-1593584785033-9c7604d0863f?q=80&w=2030&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cuisine: ["American"],
    cookingMethod: ["Fried"],
    courses: ["Breakfast"],
    prepTime: "20 mins",
    cookTime: "15 mins",
    servings: "2",
    nutritionFacts: {
      calories: "286",
      fat: "22g",
      carbs: "8g",
      protein: "15g",
    },
    tags: [],
    desc: "",
    ingredients: [
      "1.5Kg beef in 5cm pieces",
      "5 salam leaves",
      "2 sticks of lemongrass",
      "25gr dried coconut flakes",
      "200ml pineapple juice or oj",
      "1liter santen (coconut milk)",
      "4 red peppers or 2 habanero",
      "3tbps coriander seeds",
      "5cm piece of laos grated",
      "10cm ginger grated",
      "1tbsp koenjit",
      "10 cloves of garlic",
      "4 red peppers or 2 habanero",
      "Lomboks to taste (optional)",
    ],
    directions: [
      "In a kitchen mixer add peppers, garlic, laos, ginger, and the koenjit and blend to a paste",
      "Take the paste and rub it into the beef",
      "Take the beef and santen and bring to a soft boil",
      "Add the salam leaves and lemongrass(bruised) and simmer on low for 2 hours",
      "Taste add optional lomboks and salt and simmer 1 more hour stirring occasionally",
      "When the liquid has evaporated and oil floats to the top and the meat is golden brown its done",
      "Toast the coconut flakes and stir it into the stew",
      "During the cooling down the meat will soak up the liquid we rehydrate this with the pineapple juice",
    ],
    notes:
      "This is my personal favorite disg and version. Definitely recommend experimenting Add lomboks for spice or green tea for additional flavor",
    views: 200,
  },
  {
    id: 4,
    title: "Home-made Raspberry Ice Cream",
    featuredImage:
      "https://images.unsplash.com/photo-1488900128323-21503983a07e?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cuisine: ["American"],
    cookingMethod: [],
    courses: ["Dessert"],
    prepTime: "20 mins",
    cookTime: "15 mins",
    servings: "2",
    nutritionFacts: {
      calories: "286",
      fat: "22g",
      carbs: "8g",
      protein: "15g",
    },
    tags: [],
    desc: "",
    ingredients: [
      "1.5Kg beef in 5cm pieces",
      "5 salam leaves",
      "2 sticks of lemongrass",
      "25gr dried coconut flakes",
      "200ml pineapple juice or oj",
      "1liter santen (coconut milk)",
      "4 red peppers or 2 habanero",
      "3tbps coriander seeds",
      "5cm piece of laos grated",
      "10cm ginger grated",
      "1tbsp koenjit",
      "10 cloves of garlic",
      "4 red peppers or 2 habanero",
      "Lomboks to taste (optional)",
    ],
    directions: [
      "In a kitchen mixer add peppers, garlic, laos, ginger, and the koenjit and blend to a paste",
      "Take the paste and rub it into the beef",
      "Take the beef and santen and bring to a soft boil",
      "Add the salam leaves and lemongrass(bruised) and simmer on low for 2 hours",
      "Taste add optional lomboks and salt and simmer 1 more hour stirring occasionally",
      "When the liquid has evaporated and oil floats to the top and the meat is golden brown its done",
      "Toast the coconut flakes and stir it into the stew",
      "During the cooling down the meat will soak up the liquid we rehydrate this with the pineapple juice",
    ],
    notes:
      "This is my personal favorite disg and version. Definitely recommend experimenting Add lomboks for spice or green tea for additional flavor",
    views: 200,
  },
];

export const getPopularRecipes = async () => {
  const data = await recipes.filter((recipe) => recipe.views >= 100);
  return data;
};
